version: "3"

services:
  django:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/project
    working_dir: /project
    command: ./start_server.sh
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.25
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: django_playground
      TZ: Asia/Seoul

volumes:
  mysql_volume:
